---
collections:
  - name: ansible.posix
    version: 1.5.4
  - name: community.crypto
    version: 2.21.0
  - name: community.general
    version: 8.6.3
  - name: community.postgresql
    version: 3.4.1
