---
- name: Install fail2ban package
  package:
    name: fail2ban
    state: present
  tags:
    - role::fail2ban

- name: Copy fail2ban config
  copy:
    src: jail.local
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0644
  tags:
    - role::fail2ban
  notify:
    - reload fail2ban

- name: Enable fail2ban service
  service:
    name: fail2ban
    state: started
    enabled: true
  tags:
    - role::fail2ban
