$ANSIBLE_VAULT;1.1;AES256
34326663643266306162376261383566646364376639613137646237313636303430363739646631
3762303366303532386362356135313462613639323330630a333937623737366231656264623065
66643731373537326437383465386139373539653030343930646434313262386565323637356539
3962383331353331310a363163383538636133623137633930393632653930643664306663366363
62613233383935633533343861343864363131313435383237333738343766306565353463653337
35336632646538373539333563393433336532393137633062353265636533666134346464383961
33323562643462646436366133333566653565613537326137393164306165386166633539383663
38616462386432623531653564623032626632353561656431336634373530633038626665633230
33636639643037366332613264356463633262653663393531643932636335353163396431393465
3162666530626433313865656164613434626334353465333738
