title: PyDis DevOps
email: joe@jb3.dev
description: >-
  Knowledgebase for all things DevOps in Python Discord.
baseurl: "/infra"
url: "https://python-discord.github.io"
twitter_username: PythonDiscord
github_username:  python-discord

remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-feed

# Compression tuning
compress_html:
  ignore:
    envs: all

# Code block preferences
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Theme configuration
aux_links:
  "Python Discord":
    "https://pythondiscord.com/"
aux_links_new_tab: true

color_scheme: dark

# Document detection
collections:
  runbooks:
    permalink: "/:collection/:path/"
    output: true
  queries:
    permalink: "/:collection/:path"
    output: true
  general:
    permalink: "/:collection/:path"
    output: true

just_the_docs:
  collections:
    pages:
      name: Pages
    general:
      name: General
    runbooks:
      name: Runbooks
    queries:
      name: Queries
