apiVersion: apps/v1
kind: Deployment
metadata:
  name: black-knight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: black-knight
  template:
    metadata:
      labels:
        app: black-knight
    spec:
      securityContext:
        fsGroup: 2000
        runAsUser: 1000
        runAsNonRoot: true
      containers:
      - name: black-knight
        image: ghcr.io/python-discord/black-knight:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 500m
            memory: 300Mi
          limits:
            cpu: 750m
            memory: 600Mi
        envFrom:
        - secretRef:
            name: black-knight-env
        - secretRef:
            name: redis-credentials
        securityContext:
          readOnlyRootFilesystem: true
      imagePullSecrets:
        - name: ghcr-pull-secret
